fördela task annorlunda
Sponken/clover-cooked pull request #39
Opened 2021-04-20 09:57 UTC by qwerty09876-1234

behövs testas irl hur det funkar

2021-04-20 10:31 UTC, Pazzaz commented
Vi håller koll på när varje person senast klickade "Klar". Sedan om någon är ledig och inte har jobbat på länge så får de en uppgift, men inte om det är en strongdependency. Då så får den personen som precis blev klar den uppgiften. 

Vi fixade också en bugg som gjorde att typ alla uppgifter var i `strongTasks`; bara uppgifter med strongDepedendecys ska vara i `strongTasks`

2021-04-21 11:33 UTC, Sponken commented
Ni har lämnat ett todo i senaste commit-beskrivningen, är det medvetet? Bara så ni inte glömmer nåt ni tänkt lösa, men vad jag minns lät det som att det var fine att lämna

2021-04-21 11:57 UTC, Sponken requested changes
Har inte testet vid faktiskt matlagning. När jag sitter vid datorn och tester verkar det göra som förväntat, men svårt att avgöra om det som förväntas är bra eller om det finns bättre lösningar. Tills vi testat tycker jag det här funkar bra!
Lite småkommentarer om framförallt dokumentation jag tror kan fixas enkelt 😊

2021-04-21 11:57 UTC, Sponken commented on application/src/scheduler/BasicScheduler.tsx
> +    let ddd = strongDepMap.get(task.id);
Variabelnamnet är svårläst

2021-04-21 11:57 UTC, Sponken commented on application/src/scheduler/BasicScheduler.tsx
> +function prioritizeAndAssignTasks(scheduler: Scheduler, eligibleTasks: TaskID[], cook: CookID | undefined, toPreviousUser: boolean) {
Att sätta cook till undefined känns snarlikt till att sätta toPreviousUser till false. Tror att skillnaden borde dokumenteras

2021-04-21 11:57 UTC, Sponken commented on application/src/scheduler/BasicScheduler.tsx
> +function prioritizeAndAssignTasks(scheduler: Scheduler, eligibleTasks: TaskID[], cook: CookID | undefined, toPreviousUser: boolean) {
Kanske hade räckt att ge "cook" ett mer beskrivande namn

2021-04-22 11:51 UTC, Sponken commented
Problem som finns är antingen små eller svåra att fixa. Det är bra nog för nu, och definitivt bättre än innan!

2021-04-22 11:51 UTC, Sponken approved these changes
Problem som finns är antingen små eller svåra att fixa. Det är bra nog för nu, och definitivt bättre än innan!

2021-04-22 11:51 UTC, merged