Schemaläggare
Sponken/clover-cooked pull request #5
Opened 2021-03-10 10:18 UTC by Pazzaz

Detta lägger till en väldigt enkel schemaläggare.
Den lägger också till några tester med hjälp av ramverket [jest](https://jestjs.io/).

2021-03-10 10:18 UTC, Sponken commented
CLVR-102 i Jira

2021-03-10 12:12 UTC, Sponken commented
Kanske borde ha metoder för att lägga till och ta bort kockar om tanken är att man inte ska interagera direkt med listan

2021-03-10 12:13 UTC, Sponken commented
Hur lång tid det är kvar borde kanske vara med i typen

2021-03-11 14:56 UTC, erathiian requested changes
Allt ser bra ut förutom att namnen på filerna: basic_scheduler, scheduler bör ändras till camel-case med stor första bokstav

2021-03-11 15:59 UTC, Pazzaz commented
Medan vi integrerade schemaläggaren kom vi på några ändringar vi vill göra med den (t.ex att frontenden inte ska be om uppgifter, att passiva tasks hanteras annorlunda etc) så denna pull requesten är fortfarande WIP.

2021-03-12 08:12 UTC, erathiian approved these changes

2021-03-12 08:12 UTC, merged